# Netlify configuration for Vite project
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command for Vite
  command = "npm run build"

  # Publish directory (default for Vite)
  publish = "dist"

  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

# IMPORTANT : Configuration des variables d'environnement Firebase
#
# Ajoutez ces variables dans Netlify UI : Site settings > Environment variables
# Les valeurs sont dans le fichier .env (non commité dans git)
#
# Variables requises :
# - VITE_FIREBASE_API_KEY
# - VITE_FIREBASE_AUTH_DOMAIN
# - VITE_FIREBASE_DATABASE_URL
# - VITE_FIREBASE_PROJECT_ID
# - VITE_FIREBASE_STORAGE_BUCKET
# - VITE_FIREBASE_MESSAGING_SENDER_ID
# - VITE_FIREBASE_APP_ID

# Production context (main branch)
[context.production]
  environment = { NODE_ENV = "production" }

# Branch deploys context (staging, develop)
[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

# Deploy previews context (PR previews)
[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

# Redirects and rewrites for SPA (single-page application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
