# Netlify configuration for Vite project
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command for Vite
  command = "npm run build"

  # Publish directory (default for Vite)
  publish = "dist"

  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

# Note: La clé Firebase API est publique par design (sécurité via Firebase Security Rules)
# Pour que Netlify ne bloque pas le build, ajoutez dans Netlify UI :
# Site settings > Environment variables > Add a variable
# Name: SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES
# Value: [coller votre clé Firebase API depuis src/firebase.js]

# Production context (main branch)
[context.production]
  environment = { NODE_ENV = "production" }

# Branch deploys context (staging, develop)
[context.branch-deploy]
  environment = { NODE_ENV = "staging" }

# Deploy previews context (PR previews)
[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

# Redirects and rewrites for SPA (single-page application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
