[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES = "AIzaSyBcx5aW2LxZVuiiyoSlIWyf7Wyogm6Zqi4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200